# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5912f5e69aeea054ef62d3814b3c48649673fcc9e8dcbb8fed6390159c48c31f0276fdbfeadebf5e2a4bb6c5bb2797b62fffac124eb117bf1e755126a19a44ed

test:
  secret_key_base: fb741c90e7663e585a0432a2c0b19dfbd414fa1d69f6f038f2eb7f1b660d5579203a12b7179b822e3f19d1c837a8e35346921e95d80006185b5c542658f6c0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
